# execution time limiter
max_time: 180 # [s]

# when true, only the fallback solver will be used by default
enforce_fallback_solver: false

# check and fix the max deviation between the input path and the output trajectory
# by subsampling the original path with more waypoints
check_trajectory_deviation:
  enabled: true
  max_deviation: 0.5 # [m]
  max_iterations: 5 # [-]

# allows to neglect waypoints in the original path if the new path
# does not violate max distance from the original path.
# This makes for similar but sparser paths, which are easier for the
# trajectory generator to work with.
path_straightener:
  enabled: false
  max_deviation: 0.1 # [m]
  max_hdg_deviation: 0.1 # [rad]

# waypoints too close to each other cause issues in the optimization
# the incoming path is preprocessed, such waypoints are neglected
min_waypoint_distance: 0.05

# sampling dt of the output trajectory (when the path's stamp is not frmo future, 0.2 otherwise)
sampling_dt: 0.01 # [s]

# while checking the final trajectory, don't allow
# returning results which are time-wise n-times longer / shorter than
# the initial 'baca' prediction of the length
max_trajectory_len_factor: 3.0 # [-]
min_trajectory_len_factor: 0.33 # [-]

# how many times to try the plannin + sampling
n_attempts: 3 # [-]

# if the generation and sampling fails completely and the result is infeasible
# should we at least provide a naive constant-velocity solution which will
# move the drone and therefore avoid potential deadlocks?
fallback_sampling:

  enabled: true
  accel_factor: 0.75 # how fast when comparing to constraints
  speed_factor: 0.75 # how fast when comparing to constraints

  # when stopping at waypoints, stop for this time
  stopping_time: 2.0 # [s]

  # when in motion, the first waypoint segment will be longer
  # to allow transition from initial conditions
  first_waypoint_additional_stop: false

# optimizer parameters, usually left alone
time_penalty: 100
soft_constraints_enabled: true
soft_constraints_weight: 1.5
time_allocation: 2 # method, 2 = Mellinger
equality_constraint_tolerance: 1.0e-3
inequality_constraint_tolerance: 0.1
max_iterations: 10
derivative_to_optimize: 0

scope_timer:

  enabled: false
  log_filename: "" # if empty, scope timers output to terminal; otherwise log to file
